#!/bin/sh

#/usr/local/bin/python3 /data/InStock/instock/job/execute_daily_job.py

# 设置日志文件路径
LOG_FILE="../cron_job.log"

# 设置执行时间
EXECUTE_TIME=$(date +"%Y-%m-%d %H:%M:%S")

echo "[$EXECUTE_TIME] Starting daily job execution..." >> $LOG_FILE
conda activate stock_backtest_310;
python ../../instock/job/execute_daily_job.py
echo "[$EXECUTE_TIME] Daily job execution completed." >> $LOG_FILE

# 退出conda环境
conda deactivate

#mkdir -p /data/logs
#DATE=`date +%Y-%m-%d:%H:%M:%S`
#echo $DATE >> /data/logs/workdayly.log